version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"   # mapped to host 3307 to avoid conflicts

  backend:
    build: 
      context: .
      dockerfile: backend/rosm/Dockerfile
    container_name: spring-backend
    depends_on:
      - mysql
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    #   SPRING_DATASOURCE_USERNAME: root
    #   SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    #   SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"   # host:container -> access frontend via http://localhost:3000
    restart: unless-stopped

volumes:
  mysql_data:
